server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/stayhaven
spring.datasource.username=stayhaven
spring.datasource.password=stayhaven

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=stayhaven
spring.rabbitmq.password=stayhaven
